all:
  hosts:
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2223
      ansible_user: root
    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2224
      ansible_user: root
    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2225
      ansible_user: root
    localhost:
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_user: root


  children:
    app_group:
      hosts:
        managedhost-app-1: {}
        managedhost-app-2: {}
        managedhost-app-3: {}
    loadbalancer_group:
      hosts:
        localhost: {}
